site_name: Firmware Updates Integration with fwupd
site_url: https://fwupd.3mdeb.com/
theme:
    name: material
# TODO: provide logo and styling
#     favicon: images/favicon.png
#     logo: images/logo.png
# extra_css:
#     - stylesheets/extra.css
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
nav:
    - 'Intro': index.md
