name: ci
on:
  push:
    branches:
      - master
      - main
      - gh_pages
      - product_description
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - run: gem install bundler
      - run: cd docs && bundle install
      - run: cd docs && bundle exec jekyll build
